version: '2'
services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: ibird.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
      - "./docker/nginx/sslkey:/sslkey"
    links:
        - node_express
  node_express:
    build:
      context: ./docker/node
    container_name: ibird.node_express
    hostname: localhost
    volumes:
      - ".:/src"
      - ".docker_node_modules:/src/node_modules"
    working_dir: /src
    #command: [sh, -c, yarn install && yarn run build && yarn run start]
    command: [sh, -c, yarn install && yarn run dev]
    expose:
       - "3000"
  #ports: 
  #    - "3000:3000"
  postgres:
    build:
      context: ./docker/postgres
    container_name: ibird.postgres
    hostname: localhost
    environment:
      PGDATA: /var/lib/pgsql/data
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - "./db/data:/var/lib/pgsql/data"
    expose:
      - "5432"
