version: '2'
services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
    links:
      - node_express
  node_express:
    build:
      context: ./docker/node
    container_name: node_express
    hostname: localhost
    volumes:
      - ".:/src"
    working_dir: /src
    command: [sh, -c, yarn install && yarn run dev]
    ports:
      - "3000:3000"
  postgres:
    build:
      context: ./docker/postgres
    container_name: postgre
    hostname: localhost
    environment:
      PGDATA: /var/lib/pgsql/data
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - "./db/data:/var/lib/pgsql/data"
    ports:
      - "5432:5432"
